COMMERCIAL SOFTWARE LICENSE AND END USER LICENSE AGREEMENT (EULA)

Copyright © 2026 5tra83r Studios LLC. All rights reserved.

IMPORTANT: PLEASE READ THIS SOFTWARE LICENSE AGREEMENT CAREFULLY BEFORE DOWNLOADING, 
INSTALLING, COPYING, OR USING CONTEXTCUT ("SOFTWARE"). BY DOWNLOADING, INSTALLING, 
OR USING THIS SOFTWARE, YOU AGREE TO BE BOUND BY THE TERMS OF THIS AGREEMENT. 
IF YOU DO NOT AGREE, DO NOT INSTALL, COPY, OR USE THE SOFTWARE.

================================================================================
1. OWNERSHIP AND INTELLECTUAL PROPERTY
================================================================================
The Software, including its source code, Abstract Syntax Tree (AST) parsing logic, 
telemetry algorithms, documentation, brand identifiers, icons, and build artifacts, 
is the exclusive proprietary property of 5tra83r Studios LLC. ("Licensor"). 
The Software is licensed, not sold, to you ("Licensee") for use strictly under the 
terms and conditions of this Agreement. All rights not expressly granted to you are 
reserved by 5tra83r Studios LLC.

================================================================================
2. LICENSE TIERS AND PERMITTED USES
================================================================================
A. FREE CORE EDITION:
   Licensor grants Licensee a personal, non-exclusive, non-transferable, revocable 
   license to use the Free Core Edition of the Software (including Python AST pruning 
   and basic CLI capabilities) for personal, non-commercial, and evaluation purposes.

B. PRO COMMERCIAL EDITION:
   Upon purchase of a valid ContextCut Pro license key from an authorized Merchant 
   of Record (e.g. Lemon Squeezy), Licensor grants Licensee a non-exclusive, 
   commercial, worldwide license to use the Polyglot Engine (TypeScript, JavaScript, 
   custom depth filters, and advanced automation) across up to five (5) workstations 
   or development environments owned or leased by Licensee.

C. ENTERPRISE & TEAM LICENSES:
   Enterprise seat licenses allow deployment across designated organization teams 
   with multi-seat reporting and centralized configuration management as specified 
   in the applicable purchase agreement.

================================================================================
3. RESTRICTIONS
================================================================================
Licensee shall NOT:
a) Sublicense, sell, lease, rent, redistribute, host as a cloud service bureau, 
   or commercially exploit the Software except as explicitly permitted under a Pro 
   or Enterprise license;
b) Reverse engineer, decompile, disassemble, or attempt to derive the source code 
   of proprietary components or license verification systems;
c) Modify, obscure, or remove any copyright notices, trademarks, or proprietary 
   legends belonging to 5tra83r Studios LLC.;
d) Use the Software to develop, train, or benchmark a competing context pruning 
   product;
e) Use the Software in violation of any applicable local, state, national, or 
   international laws, or to process malicious payloads or malware.

================================================================================
4. PRIVACY, TELEMETRY, AND AI SAFETY
================================================================================
a) 100% Local Processing: The Software operates locally on Licensee's workstation. 
   Licensor does not collect, transmit, or inspect Licensee's source code, prompts, 
   or proprietary trade secrets.
b) Local Analytics: Telemetry records generated by the Software are stored locally 
   on Licensee's machine (~/.contextcut/history.jsonl) and remain in Licensee's 
   exclusive possession.
c) AI Safety: The Software includes automated heuristics designed to redact 
   credentials and API keys in memory. While Licensor strives to maximize detection 
   accuracy, Licensee remains ultimately responsible for the security and secrecy 
   of their private keys and confidential files.

================================================================================
5. DISCLAIMER OF WARRANTIES
================================================================================
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED 
"AS IS" AND "AS AVAILABLE," WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND. 
5TRA83R STUDIOS LLC. EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED, OR 
STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS 
FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. LICENSOR DOES NOT WARRANT 
THAT THE SOFTWARE WILL BE ERROR-FREE, UNINTERRUPTED, OR COMPATIBLE WITH EVERY 
THIRD-PARTY AI AGENT OR RUNTIME.

================================================================================
6. LIMITATION OF LIABILITY
================================================================================
IN NO EVENT SHALL 5TRA83R STUDIOS LLC., ITS OFFICERS, DIRECTORS, EMPLOYEES, OR 
AFFILIATES BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE, OR 
CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF PROFITS, DATA LOSS, BUSINESS INTERRUPTION, 
OR COSTS OF PROCUREMENT OF SUBSTITUTE GOODS) ARISING OUT OF OR IN CONNECTION 
WITH THE USE OR INABILITY TO USE THE SOFTWARE, REGARDLESS OF THE THEORY OF 
LIABILITY (CONTRACT, TORT, OR OTHERWISE), EVEN IF ADVISED OF THE POSSIBILITY 
OF SUCH DAMAGES. IN NO EVENT SHALL LICENSOR'S TOTAL CUMULATIVE LIABILITY EXCEED 
THE AMOUNT ACTUALLY PAID BY LICENSEE FOR THE SOFTWARE IN THE TWELVE (12) MONTHS 
PRECEDING THE CLAIM.

================================================================================
7. GOVERNING LAW AND SEVERABILITY
================================================================================
This Agreement shall be governed by and construed in accordance with the laws 
of the United States of America. If any provision of this Agreement is held to 
be unenforceable or invalid, that provision shall be reformed to the minimum 
extent necessary to make it enforceable, and the remaining provisions shall remain 
in full force and effect.

For licensing inquiries, enterprise terms, or commercial permissions:
Contact: legal@5tra83rstudios.com
Website: https://5tra83rstudios.com
